language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..

############### Configuration cobertura

##script: mvn cobertura:cobertura-integration-test -P test-consumer,test-business

#############Jacoco


after_success:
  - bash <(curl -s https://codecov.io/bash)
