language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..
##sonarConfig
addons:
  sonarcloud:
    organization: "ndasilva1408"
    token:
      secure: "DKVxgoQLhLX1hOfRdXPot1x9KIyJR6vzlCVqdi+Jpp5NzpKbLifsVmskviFIAouSFemMxpF5jCl7Y2w6uOMp2iEe6dIQ6xmgm1iCe9ojglnJ3gdjVT9EAshM/GwZQO5UBmhWC5xDQ1XC98BefvTqxYWuOmtCK6OcsHoZkbf6Emi+0Qf166RkJI4FkCGeM3S2ZVq2DpkLVAYyVUxatwel/x1+x1zUwlEKgM5F/kz/OFSDnLCA2X6bPNMQmIsy6lbWY+NJMmV1Zz2w4inVz6xo+E2iZN6mHfvLrMU6Yz3aywtaHaVz8mAe2A6VAs3706NvdlG8tPXAAQCQinU/74DBEQ6NLF+sfxoNwcAMxurtGF+fazkH3qQL3Z0XROv0GLx6QgcqhU9eFTVnpZwbpklchgIxE4tn+6UYEpz2dQtCiDmc+wk5KIE1FA7AZbMFqVm40u6N41k83bBsfIQ1PtBmoAM1qMgTLSzly+YPUMhl6zDYyNhM45uU77FYqrDuyT7aYPu41GeI6nr4xcFRP9GCmV0lEa1uOoXU5UFmp7j1jRTIMcuvZdxH3Ec2ZzgRcfTBAsn2aiDt5nlniF0ZoTm+GMjArxnOHJWdJb+eQAqfJub/u8+Rm0wo6uXTQL7yK4gaMt1wuPG2UGnj8p9/eNLU9dLm/5WjcJvcF3DDqukAUEE=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  -mvn sonar:sonar -Dsonar.projectKey=ndasilva1408_myerp2

after_success:
  - bash <(curl -s https://codecov.io/bash)
