language: java

jdk: -openjdk8

sudo : required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..

script:
 - mvn test -Ptest-consumer,test-business

after_success:
  - bash <(curl -s https://codecov.io/bash)
