language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a
  - cd ../..

############### Configuration cobertura

script: mvn cobertura:cobertura-integration-test -Ptest test-business

after_success:
  - bash <(curl -s https://codecov.io/bash)
